# ════════════════════════════════════════════════════════════════════════
# BodyBuddy — Production Dockerfile
#
# Multi-stage build targeting Next.js's "standalone" output, so the final
# runtime image only ships the compiled server plus the exact node_modules
# it needs — not the full dev toolchain, source maps, or build cache.
#
# Build:
#   docker build -t bodybuddy .
#
# Run:
#   docker run -p 3000:3000 --env-file .env.local bodybuddy
#
# (Or use `docker compose up` — see docker-compose.yml, which wires this
# image up with an env file and a healthcheck in one step.)
# ════════════════════════════════════════════════════════════════════════

# ── Stage 1: deps — install dependencies only (best layer-cache reuse) ────
FROM node:22-alpine AS deps
WORKDIR /app

# libc6-compat is recommended by Next.js for some native deps on Alpine
RUN apk add --no-cache libc6-compat

COPY package.json package-lock.json* ./
RUN npm ci

# ── Stage 2: builder — compile the Next.js production build ───────────────
FROM node:22-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build-time environment. NEXT_PUBLIC_* values are baked into the client
# bundle at build time, so they're accepted as build args here and also
# exported as env vars for the `next build` step itself. Server-only
# secrets (SUPABASE_SERVICE_ROLE_KEY, RAZORPAY_KEY_SECRET, etc.) are never
# needed at build time — only at container runtime — so they are NOT
# declared here; pass them via `docker run --env-file` / compose instead.
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_RAZORPAY_KEY_ID
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL \
    NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY \
    NEXT_PUBLIC_RAZORPAY_KEY_ID=$NEXT_PUBLIC_RAZORPAY_KEY_ID \
    NEXT_TELEMETRY_DISABLED=1

RUN npm run build

# ── Stage 3: runner — minimal production runtime image ─────────────────────
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

# Run as a non-root user
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# Standalone server + the assets it needs to serve directly
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
  CMD node -e "fetch('http://127.0.0.1:'+(process.env.PORT||3000)).then(r=>process.exit(r.ok||r.status<500?0:1)).catch(()=>process.exit(1))"

# server.js is generated by `next build` with output: "standalone"
CMD ["node", "server.js"]
