// ── CSV raw import declarations ───────────────────────────────────────────
// Tells TypeScript that any `import x from "…/foo.csv?raw"` returns a string
// (the raw CSV text, bundled by webpack asset/source or raw-loader).
declare module "*.csv?raw" {
  const content: string;
  export default content;
}

// Alias for the catalog CSV imported without the ?raw suffix by some paths
declare module "*.csv" {
  const content: string;
  export default content;
}

// ── masterFoodDatabase.json ───────────────────────────────────────────────
// This file is generated by `scripts/buildFoodDatabase.ts` and is NOT
// committed to source control. When it's absent (e.g. fresh clone, CI),
// TypeScript should still compile without errors.
declare module "@/data/masterFoodDatabase.json" {
  // Each entry has at minimum the fields masterFoods.ts reads.
  // The shape is intentionally loose — masterFoods.ts casts to MasterFoodEntry[].
  const value: unknown[];
  export default value;
}
